
import 'dotenv/config';
import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

// -----------------------------------------------------------------------------
// 配置
// -----------------------------------------------------------------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');
const DB_PATH = path.join(PROJECT_ROOT, 'data', 'fomorader.db');
const FEISHU_WEBHOOK = process.env.FEISHU_WEBHOOK || '';

// -----------------------------------------------------------------------------
// 类型定义
// -----------------------------------------------------------------------------
interface ScoreRow {
  title: string;
  title_zh: string;
  summary: string;
  summary_zh: string;
  url: string;
  total_score: number;
  author?: string;
  published_at: string;
}

// -----------------------------------------------------------------------------
// 飞书消息构建器
// -----------------------------------------------------------------------------
function buildFeishuCard(items: ScoreRow[]) {
  // 格式化日期为: 3月13日 08:00
  const now = new Date();
  const month = now.getMonth() + 1;
  const day = now.getDate();
  const hour = String(now.getHours()).padStart(2, '0');
  const minute = String(now.getMinutes()).padStart(2, '0');
  const fullDateStr = `${month}月${day}日 ${hour}:${minute}`;
  
  // 顶部卡片
  const header = {
    template: 'blue',
    title: {
      content: `📡 FOMORader 日报 (${fullDateStr})`,
      tag: 'plain_text'
    }
  };

  const elements: any[] = [];

  // Top 10 items
  items.slice(0, 10).forEach((item, index) => {
    const title = item.title_zh || item.title;
    const score = item.total_score.toFixed(1);
    const summary = item.summary_zh || item.summary;
    const author = item.author ? ` · @${item.author}` : '';
    
    // 格式化发布时间: 03/12 14:30
    const pubDate = new Date(item.published_at);
    const pubMonth = String(pubDate.getMonth() + 1).padStart(2, '0');
    const pubDay = String(pubDate.getDate()).padStart(2, '0');
    const pubHour = String(pubDate.getHours()).padStart(2, '0');
    const pubMinute = String(pubDate.getMinutes()).padStart(2, '0');
    const pubTimeStr = `${pubMonth}/${pubDay} ${pubHour}:${pubMinute}`;

    // 分隔线
    if (index > 0) {
      elements.push({ tag: 'hr' });
    }

    // 标题 + 分数
    elements.push({
      tag: 'div',
      text: {
        content: `**[${score}分]** [${title}](${item.url})`,
        tag: 'lark_md'
      }
    });

    // 摘要 + 作者 + 发布时间
    elements.push({
      tag: 'div',
      text: {
        content: `${summary}${author}\n**发布于**: ${pubTimeStr}`,
        tag: 'lark_md'
      }
    });
  });

  // 底部链接
  elements.push({ tag: 'hr' });
  elements.push({
    tag: 'note',
    elements: [
      {
        content: `Generated by FOMORader · [查看完整榜单](${process.env.WEB_URL || 'http://localhost:5173'})`,
        tag: 'lark_md'
      }
    ]
  });

  return {
    msg_type: 'interactive',
    card: {
      header,
      elements
    }
  };
}

// -----------------------------------------------------------------------------
// 推送逻辑
// -----------------------------------------------------------------------------
async function pushToFeishu(payload: any) {
  if (!FEISHU_WEBHOOK) {
    console.warn('⚠️ FEISHU_WEBHOOK not configured in .env');
    return;
  }

  try {
    const res = await fetch(FEISHU_WEBHOOK, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    const data = await res.json();
    console.log('Feishu response:', data); // Add log to debug
    if (data.code !== 0) {
      console.error('❌ Feishu push failed:', data);
    } else {
      console.log('✅ Feishu push success!');
    }
  } catch (e) {
    console.error('❌ Feishu network error:', e);
  }
}

// -----------------------------------------------------------------------------
// 主函数
// -----------------------------------------------------------------------------
async function main() {
  const db = new Database(DB_PATH);
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  
  // Read limit from environment variable (default 10)
  // This allows dynamic configuration without changing code
  const pushLimit = Number(process.env.PUSH_LIMIT) || 10;

  // 获取最近24小时的高分内容
  // 正常运行模式下严格限制为最近24小时
  // 使用 --force 参数可忽略时间限制（仅用于调试）
  const timeFilter = force ? '1970-01-01T00:00:00.000Z' : new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  
  console.log(`🔍 Fetching items published after: ${timeFilter} (Limit: ${pushLimit})`);

  const rows = db.prepare(`
    SELECT 
      h.id,
      h.title, s.title_zh, 
      h.summary, s.summary_zh, 
      h.url, s.total_score, s.author, h.published_at
    FROM hotspots h
    JOIN scores s ON h.id = s.hotspot_id
    WHERE datetime(h.published_at) > datetime(?)
      AND h.id NOT IN (SELECT hotspot_id FROM push_history)
    ORDER BY s.total_score DESC
    LIMIT ?
  `).all(timeFilter, pushLimit) as (ScoreRow & { id: number })[];

  if (rows.length === 0) {
    console.log('⚠️ No new high-score items found (last 24h).');
    if (!force) {
      console.log('💡 Tip: No items to push. This is expected if no new high-quality content was found today.');
    }
    return;
  }

  console.log(`✅ Found ${rows.length} items to push.`);
  const card = buildFeishuCard(rows);
  
  await pushToFeishu(card);

  // Record push history
  const insertHistory = db.prepare(`INSERT OR IGNORE INTO push_history (hotspot_id, pushed_at) VALUES (?, datetime('now'))`);
  db.transaction(() => {
    for (const row of rows) {
      insertHistory.run(row.id);
    }
  })();

  db.close();
}

import { pathToFileURL } from 'url';

// Allow running directly
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}

export { main as pushFeishuDaily };
